add default timeout being added to the visit
YusukeIwaki/capybara-playwright-driver pull request #58
Opened 2023-03-22 10:07 UTC by ankitsinghaniyaz

2023-03-22 10:49 UTC, ankitsinghaniyaz commented
closes #57 

The default max timeout was not being passed to the navigational timeout.

2023-04-02 12:09 UTC, ankitsinghaniyaz commented
Please it's not stale. We need to discuss and merge it.

2023-04-09 16:04 UTC, YusukeIwaki requested changes

2023-04-09 16:04 UTC, YusukeIwaki commented on lib/capybara/playwright/browser.rb
> +          @playwright_page.capybara_current_frame.goto(url, timeout: Capybara.default_max_wait_time * 1000)
`Capybara.default_max_wait_time` is 2 by default.
It is too short for navigation timeout and this change would break existing tests for many users.

2023-04-09 16:35 UTC, ankitsinghaniyaz commented
How do you recommend this be done? As this is a major issue.

On Sun, Apr 9, 2023, 21:34 Yusuke Iwaki ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In lib/capybara/playwright/browser.rb
> <https://github.com/YusukeIwaki/capybara-playwright-driver/pull/58#discussion_r1161307531>
> :
>
> > @@ -65,7 +65,7 @@ def visit(path)
>              path
>            end
>
> -          @playwright_page.capybara_current_frame.goto(url)
> +          @playwright_page.capybara_current_frame.goto(url, timeout: Capybara.default_max_wait_time * 1000)
>
> Capybara.default_max_wait_time is 2 by default.
> It is too short for navigation timeout and this change would break
> existing tests for many users.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/YusukeIwaki/capybara-playwright-driver/pull/58#pullrequestreview-1376929904>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACWOTFLJIXBWWZMKTF4RPGTXALMY7ANCNFSM6AAAAAAWDS6ZEI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-04-09 17:32 UTC, YusukeIwaki commented
The main cause of the issue is the incorrect usage of `timeout` of Capybara::Playwright::Driver.
Capybara::Selenium::Driver uses the parameter for setting read_timeout of Selenium driver, so I think it is reasonable to use the `timeout` parameter for setting the default navigation timeout of Playwright.

2023-04-09 17:33 UTC, YusukeIwaki commented
I'm now working the fix https://github.com/YusukeIwaki/capybara-playwright-driver/pull/59

2023-04-10 01:03 UTC, YusukeIwaki commented
I fixed the issue #57 with another direction in #59.
Thank you for your proposal and patients. The fix will be released soon.

2023-04-10 01:04 UTC, closed without merging